server:
  port: 8080

spring:
  application:
    name: mini-3-back

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/mydb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

cloud:
  aws:
    region: ap-northeast-2 #수정 필요
    s3:
      bucket: ${S3_BUCKET_NAME:awslab2026-bucket-test}
